# Generated by Django 5.2.1 on 2025-05-31 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_subscription_created_at_alter_subscription_author_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Подписка",
                "verbose_name_plural": "Подписки",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["email"],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
